version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ecom_db
    ports:
      - "5433:5432" # port_me:port_docker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: